import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "react-hot-toast";
import { NextAuthProvider } from "./(auth)/signin/session";
import StoreProvider from "./StoreProvider";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import { Roboto } from "next/font/google";
import { cookies } from "next/headers";
import { ThemeProvider } from "./context/ThemeContext";
import AppTheme from "@/components/custom/themes/AppTheme";
import "./globals.css";

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const rawTheme = (await cookies()).get("theme")?.value;
  const themeFromCookie =
    rawTheme === "dark" || rawTheme === "light" ? rawTheme : "light";

  return (
    <html lang="en" className={roboto.variable}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased dark:bg-gray-800`}
      >
        <AppRouterCacheProvider options={{ key: "css", enableCssLayer: true }}>
          <ThemeProvider initialMode={themeFromCookie}>
            <AppTheme>
              <StoreProvider>
                <Toaster position="top-right" reverseOrder={false} />
                <NextAuthProvider>{children}</NextAuthProvider>
              </StoreProvider>
            </AppTheme>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
